Test new github features
robertpainsi/Catroid pull request #8
Opened 2016-09-15 11:21 UTC by robertpainsi

Test

2016-09-15 11:21 UTC, robertpainsi commented on catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorCategoryListFragment.java
> +			R.string.formula_editor_sensor_drone_record_sadadready, R.string.formula_editor_sensor_drone_recording,
Test

2016-09-15 11:21 UTC, robertpainsi commented on catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorCategoryListFragment.java
> +			case 1:das
Das is das das das

2016-09-15 11:21 UTC, robertpainsi commented on catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorCategoryListFragment.java
> +		FragmentManager fragmentManager = activityasd.getFragmentManager();
And das

2016-09-15 11:21 UTC, robertpainsi commented on catroid/src/main/java/org/catrobat/catroid/ui/fragment/FormulaEditorCategoryListFragment.java
> +		n = fragmentManager.beginTransaction();
this is good

2016-09-15 11:21 UTC, robertpainsi reviewed
Done

2016-09-15 11:24 UTC, robertwhitebit requested changes
Please see @robertpainsi changes :smirk_cat:

2016-09-15 11:26 UTC, robertwhitebit requested changes
asdsd

2016-09-15 11:33 UTC, robertpainsi reviewed
asd

2016-09-21 18:07 UTC, robertwhitebit approved these changes
Looks good

2016-11-10 16:42 UTC, closed without merging